### ISSUE TITLE
dates incorrectly reported in output

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#12]
Dates are coming back have month and day always equal to 0.
i.e. 2010-00-00 for every day during diurnal periods pulled during a month:

api url: http://climate.ncsu.edu/api/alpha/api_request.php?&var=lat,lon,datetime,temp,wind_u,wind_v,ws,precip&loc=state=NC,SC%20AND%20type=ASOS&start=2010-06-01%2007:00:00&end=2010-07-01%2007:00:00&int=12%20hour&obtype=H&timezone=EST&qclimit=1

**Comment by jamcguir** [comment]
Bug fixed in database for date format string. It was improperly added as "Y:i:m H:i:s", now fixed to the correct "Y-m-d H:i:s"
