### ISSUE TITLE
int overides dates selected 

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#15]
If the aggregation interval is larger than the dates requested.  It includes all the dates from the start of the aggregation period to the end of the aggregation period regardless if the end time is not at the end of the aggregation period.

For example If i request monthly data, but only pick 7 days for which to pull my sum it still uses the entire month (30 days -> 720 values) instead of 168.  This is a user specified error, but returns info that may be misunderstood. Not sure best way to handle.  Error message? Just use start / end date data?

How to select custom accumulation / aggregation period?

Query:
http://climate.ncsu.edu/api/alpha/api_request.php?&var=sumprecip&loc=station=KFLO&start=2006-06-01%2000:00:00&end=2006-06-06%2012:59:59&int=1%20month&obtype=H&timezone=EST&qclimit=1&output=html

**Comment by jamcguir** [comment]
This should be now resolved with ncsco/api@b8364480b65d60fcb2ee20e6a7d223be51289021
