### ISSUE TITLE
accumulations not matching when selecting different intervals

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#16]
The following 2 queries should yield the same precip totals:

This one gives: 8.05 inches when you add up all the hours
http://climate.ncsu.edu/api/alpha/api_request.php?&var=precip&loc=station=KCAE&start=2006-06-01 01:00:00&end=2006-07-01 00:00:00&int=1 hour&obtype=H&timezone=EST&qclimit=1&output=html&missing=0

This one returns back the value of 1.32 inches
http://climate.ncsu.edu/api/alpha/api_request.php?&var=precip&loc=station=KCAE&start=2006-06-01 01:00:00&end=2006-07-01 00:00:00&int=1 month&obtype=H&timezone=EST&qclimit=1&output=html&missing=0

**Comment by jamcguir** [comment]
So there is an issue with your 2nd request:

You want a month period of data, but technically, that isn't a full month, as you are one hour short. Any thoughts on how to handle that?

**Comment by jamcguir** [comment]
The latest commit ncsco\api@b8364480b65d60fcb2ee20e6a7d223be51289021 resolves this issue
