### ISSUE TITLE
SQL error trying to pull data for specific states

### ISSUE THREAD

**Issue by DENR-Dave** [ncsco/api-help#17]
Trying to pull data from NC and SC as a test using the following (hash removed for security) ... see bottom of this post for more information:

http://climate.ncsu.edu/api/v1.0-beta1/api_request.php?loc=state=nc,sc

That URL resulted in the following SQL error:

Unknown column 'temp' in 'field list' with data_q: SELECT station,CONVERT_TZ(ob,'EST','US/Eastern') as ob,"US/Eastern" as timezone,obtype,CONVERT_TZ(IF(MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1) >= 0.5,DATE_ADD(ob,INTERVAL (3600 - 3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND),DATE_SUB(ob,INTERVAL (3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND)),'-05:00','US/Eastern') as datetime,TIMESTAMPDIFF(SECOND,IF(MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1) > 0.5,DATE_ADD(ob,INTERVAL (3600 - 3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND),DATE_SUB(ob,INTERVAL (3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND)),`ob`) as diff_sec,ob as db_ob,IF(MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1) >= 0.5,DATE_ADD(ob,INTERVAL (3600 - 3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND),DATE_SUB(ob,INTERVAL (3600*MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1)) SECOND)) as roundob,FLOOR(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600) as sqlfull,MOD(TIMESTAMPDIFF(SECOND,CONVERT_TZ('2015-04-04 07:58:00','US/Eastern',"-05:00"),ob)/3600,1) as sqlstep,"ECONET" as `network`,"temp" as variable,ROUND(temp,1) as `value`,"" as `flag`,"" as `score`,"C" as `unit`,"I" as `vartype`,"M" as `nettype`,"cronos.daily" as dbtable,IF(temp = NULL, 0, 1) as `count`,1 as `rows` FROM cronos.daily as m WHERE station IN ("AURO","BEAR","BUCK","BURN","CAST","CLA2","CLAY","CLIN","DURH","FLET","FRYI","GOLD","JACK","JEFF","KINS","LAKE","LAUR","LEWS","LILE","MITC","NCAT","NEWL","OXFO","PLYM","REED","REID","ROCK","SALI","SASS","SILR","SPIN","SPRU","TAYL","WAYN","WHIT","WILD","WILL","WINE") AND ob >= CONVERT_TZ("2015-04-04 07:28:00",'US/Eastern','-05:00') AND ob <=CONVERT_TZ("2015-04-06 08:28:00",'US/Eastern','-05:00') AND obtype IN ("O") ORDER BY ob ASC, ABS(diff_sec) ASC

I also tried: http://climate.ncsu.edu/api/v1.0-beta1/api_request.php?state=nc,sc&start=-1 day which did NOT throw an error but I also did not get the data I was expecting. It looks like it defaulted to the LAKE data that I get without any parameters being passed.

**Comment by jamcguir** [comment]
This issue has been resolved. Thank you for your report.

For the station location, it must be defined with "loc=state=nc,sc". This is done in order to allow for multiple ways to sort your location, instead of just "state".

**Comment by DENR-Dave** [comment]
Thank you for correcting the SQL error but the data being returned is not corrected. After 913 lines of what appears to be valid data but is proceeded by a # so it is a comment, there are another 22,602 lines of data that are nothing but mostly MV (missing values). The URL for this result was: 

loc=state=nc,sc&start=-1 day

Here is what the start of those 22 thousand lines looks like ... something is wrong with this picture:

##Parameter Metadata
##parameter,description,height,unit
##station,Station ID,0m,ID
##datetime,Valid Datetime,0m,US/Eastern
##temp,Air Temperature,2m,C
##precip,Accumulated Precipitation,2m,in
##
##Missing values are coded as MV
##
##The maximum Quality Control score allowed for values is 1
##
##Variable Type Code Format = (nettype)(vartype)(obtype)
##codetype:code1=name1,code2=name2,...,codeN=nameN
##nettype:S=Static,M=Measured,C=Calculated
##vartype:A=Accumulated,G=Grouped/Aggregated,I=Instantaneous,M=Metadata,S=Searched/Matched
##obtype:N=1981 - 2010 Normal Value,D=Daily Observation,H=Hourly Observation,O=Minute Observation,R=Recent,S=Special Observation
##
##API Execution time: 13.769 sec
##Query Execution time: 1.298 sec
##Number of data entries scanned: 889547
##Number of data entries used: 69269
##Ran at: 2015-04-07 15:16:24 EDT
##
## For help with your request, include "&help" in the URL above
## Report bugs or issues at: https://github.com/ncsco/api-help/issues/
##
station;unit,datetime;unit,temp;unit;score;type;count;rows,precip;unit;score;type;count;rows
MV;ID,MV;US/Eastern,MV;MV;MV;MV;0;0,MV;MV;MV;MV;0;0
MV;ID,MV;US/Eastern,MV;MV;MV;MV;0;0,MV;MV;MV;MV;0;0
MV;ID,MV;US/Eastern,MV;MV;MV;MV;0;0,MV;MV;MV;MV;0;0

**Comment by jamcguir** [comment]
This will be fixed in a new release, still working on some situational bugs. Will notify when new release is available.

**Comment by DENR-Dave** [comment]
OK thanks for letting me know. Can’t do a lot with it the way it is right now ☺

Dave Martin
NC Division of Water Resources
(919) 707-9154

**Comment by jamcguir** [comment]
Okay, give this a try now. Changes have been applied and the beta version has been updated.

**Comment by DENR-Dave** [comment]
OK that looks a bit better. Still got 217 lines of comments that appears to list all of the stations that data is going to be returned for. Can't imagine that is something you would want to do in production as it is all flagged as comments so a great waster of bandwidth.

Other than that, which is not a show stopper at all, it looks like I got some good data this time.

**Comment by jamcguir** [comment]
Yes, that is done by design to give information about each station.

In order to eliminate that, please add &meta=0 to your URL

http://climate.ncsu.edu/api/v1.0-beta1/api_request.php?loc=state=nc,sc&meta=0

**Comment by DENR-Dave** [comment]
Ah OK thanks.
