### ISSUE TITLE
Parameter values returned vary for a given date/time record when the data interval is changed.

### ISSUE THREAD

**Issue by gsbuol** [ncsco/api-help#19]
Setting the data request interval (int) to 1, 5, 10, 20, 30, or 60 minutes returns different parameter values for a returned date/time record.  Using a request interval of 1 minute for an ECONet station as the standard for all over intervals the API currently produces the following results:

int=5 minute:  Parameter values returned for a date/time record are values 2 minutes ahead of the record date/time.  The 07:05:00 record shows data from the 07:07:00 record returned using a 1 minute interval.

int=10 minute: Parameter values returned for a date/time record are values 5 minutes behind the record date/time.  The 07:00:00 record shows data from the 06:55:00 record returned using a 1 minute interval.  Also, the 07:50:00 record shows data from the 07:45:00 1 minute interval records while the 08:00:00  record shows data from the 08:05:00 1 minute interval records.  In this case, the parameter data is 20 minutes apart instead of 10 minutes.

int=20 minute: Parameter values returned for a date/time record are values 10 minutes behind the record date/time.  The 07:00:00 record shows data from the 06:50:00 record returned using a 1 minute interval.  Also, the 07:40:00 record shows data from the 07:30:00 1 minute interval records while the 08:00:00  record shows data from the 08:10:00 1 minute interval records.  In this case, the parameter data is 30 minutes apart instead of 20 minutes.

The offset gets progressively worse as the time interval increases.  It is important to have all instantaneous parameter values for a reported date/time to be consistent across all report intervals to ensure proper graphing and calculations.

**Comment by jamcguir** [comment]
Thank you for the information. Can you please provide a sample request URL so that I can duplicate this? 

Make sure to edit out your username and hash. Thanks!

**Comment by gsbuol** [comment]
I am using the following URL:
http://climate.ncsu.edu/api/beta/api_request.php?loc=station=LAKE&end=-15 day 6am&start=-15 day 8am&obtype=O&var=leafwetness,sr,par,temp,rh,precip&int=1 minute

**Comment by jamcguir** [comment]
I have reworked the calculation of the nearest observation for the instantaneous parameters. By running your example URL, I am now get minute observation times for each variable that are identical to the "datetime".

If you add "&attr=time,count" to your query, you should get back the actual times for each parameter. Please note that for accumulated variables (precip), the date shown will not be entirely useful. I am working on the best way to handle that scenario.

Please let me know if this helps resolve your issue.

**Comment by gsbuol** [comment]
Everything seems to working as expected now.  Initial checks using different interval values are returning instantaneous parameter values corresponding to the reported date/time.  Thanks.

**Comment by jamcguir** [comment]
Marked as fixed with commit ncsco/api@a0a86bbbe18012cb1be7ec3a07eec6e38a3719bc
