### ISSUE TITLE
output format bug

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#2]
Types and scores are reported incorrectly.
sample request:
http://nc-climate.ncsu.edu/api/alpha/api_request.php?&var=lat,lon,elev,temp,rh,dew,ws,wd,precip&loc=type=ASOS,ECONET&start=2009-06-24%2017:30:00&end=2009-06-24%2018:29:00&obtype=H&attr=value,score

**Comment by jamcguir** [comment]
The scores issue should be fixed. There is a type bug that resonates with variables that accept both hourly and special obs (such as temps), investigating further

**Comment by jamcguir** [comment]
Bug addressed in ncsco/api@f8556480847fddd71238d363e894d8f584a2f756

Multiple obtypes will be concatenated with a plus sign. Documentation has been updated to reflect this.
