### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by rebobyak** [ncsco/api-help#22]
I've tried changing the timezone to other PHP supported time zones and the results still come out in Eastern time.

**Comment by jamcguir** [comment]
Are you seeing the same values for the time, regardless of the timezone?

Using the following example, data should appear as intended.

https://climate.ncsu.edu/api/beta/data.php?loc=station=LAKE&timezone=UTC&start=8am&end=11pm&attr=value
`station;network;lat;lon,datetime;timezone,temp;rows,precip;rows
LAKE;ECONET;35.72816;-78.67981,2016-06-21 08:00:00;UTC,20.8;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 09:00:00;UTC,19.7;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 10:00:00;UTC,19.2;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 11:00:00;UTC,19.5;1,0.00;1`

https://climate.ncsu.edu/api/beta/data.php?loc=station=LAKE&start=8am&end=11am&attr=value
`station;network;lat;lon,datetime;timezone,temp;rows,precip;rows
LAKE;ECONET;35.72816;-78.67981,2016-06-21 08:00:00;US/Eastern,20.4;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 09:00:00;US/Eastern,22.3;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 10:00:00;US/Eastern,24.4;1,0.00;1
LAKE;ECONET;35.72816;-78.67981,2016-06-21 11:00:00;US/Eastern,25.9;1,0.00;1`

**Comment by rebobyak** [comment]
I tried to replicate the error and now it's working fine... So I guess problem solved
