### ISSUE TITLE
ECONET daily precipitation not daily?

### ISSUE THREAD

**Issue by rvcumbie** [ncsco/api-help#25]
Description of problem:
I'm trying to get daily precipitation from ECONet, but it's not giving me what I expect.

Steps to Reproduce:
1.  Running this URL:
https://climate.ncsu.edu/api/beta/data.php?loc=station=LAKE&var=precip&start=2016-11-02&end=2016-12-10&int=1%20day&meta=1&missing=-999&obtype=D&hash=
2. I have also tried obtype=D,H, or just leaving off

Actual Results:
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-02 00:00:00 EDT;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-03 00:00:00 EDT;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-04 00:00:00 EDT;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-05 00:00:00 EDT;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-06 00:00:00 EDT;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-07 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-08 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-09 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-10 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-11 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-12 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-13 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-14 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-15 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-16 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-17 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-18 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-19 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-20 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-21 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-22 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-23 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-24 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-25 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-26 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-27 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-28 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-29 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-11-30 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-01 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-02 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-03 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-04 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-05 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-06 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-07 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-08 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-09 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1
station;LAKE;ECONET;NA;S;M;D;1,datetime;2016-12-10 00:00:00 EST;US/Eastern;NA;S;M;O+S+H+D;1

Expected Results:
(FROM CRONOS QUERY):

Date/Time (EST)	1m Daily Precipitation (in)
11/2/2016	0
11/3/2016	0
11/4/2016	0.05
11/5/2016	0
11/6/2016	0
11/7/2016	0
11/8/2016	0
11/9/2016	0
11/10/2016	0
11/11/2016	0
11/12/2016	0
11/13/2016	0.13
11/14/2016	0.17
11/15/2016	0
11/16/2016	0
11/17/2016	0
11/18/2016	0
11/19/2016	0
11/20/2016	0
11/21/2016	0
11/22/2016	0
11/23/2016	0
11/24/2016	0.05
11/25/2016	0
11/26/2016	0
11/27/2016	0
11/28/2016	0
11/29/2016	0.01
11/30/2016	0.15
12/1/2016	0
12/2/2016	0
12/3/2016	0
12/4/2016	0.29
12/5/2016	0.44
12/6/2016	0.36
12/7/2016	0
12/8/2016	0
12/9/2016	0
12/10/2016	0

API Version Used:
API v1.0.167-Beta (fb4d882)

Additional info:
I've run this with added parameters tempmax and tempmin (as a sanity check) and am getting appropriate values back for them.

[X ] I have removed my user hash from this post

**Comment by jamcguir** [comment]
Revisited issue with latest beta, v1.0.429-Beta (f98b3c3).

Issue has since been resolved. My apologies for not closing ticket earlier
