### ISSUE TITLE
Builder query failed - time frequency must be a positive value

### ISSUE THREAD

**Issue by W1DJM** [ncsco/api-help#27]
Description of problem:

Instead of data being returned (in CSV format) I received an error about data being invalid

Steps to Reproduce:

Try to run this query with a valid hash added at the end.

https://climate.ncsu.edu/api/beta/data?loc=310296,310300,310530,310531,310724,311055,311624,311690,311975,312200,312238,312724,312837,313017,313555,313630,313638,314020,314055,314260,314496,314860,314938,315123,315182,315340,315356,315838,315890,315913,316108,316256,316805,316853,317069,317486,317845,318158,318292,318694,318744,319122,319123,319147,319440,319457,319675,AVLthr,KAVL,HSEthr,CLTthr,KNKT,KCLT,ECGthr,KGSO,GSOthr,LBTthr,RDUthr,ILMthr&var=location,data_hourly,precip,watertemp,watertempmean&start=1950-01-01 00:00&end=2020-01-28 23:59&int=0 SECOND&output=csv&attr=var,value,value_accum,unit,score,nettype,vartype,obtype,obnum,location,datetime&order=datetime,location&hash=

Actual Results:

code: 400 message: Uh oh, a FATAL ERROR! source: https://climate.ncsu.edu/api/beta/data?loc=310296,310300,310530,310531,310724,311055,311624,311690,311975,312200,312238,312724,312837,313017,313555,313630,313638,314020,314055,314260,314496,314860,314938,315123,315182,315340,315356,315838,315890,315913,316108,316256,316805,316853,317069,317486,317845,318158,318292,318694,318744,319122,319123,319147,319440,319457,319675,AVLthr,KAVL,HSEthr,CLTthr,KNKT,KCLT,ECGthr,KGSO,GSOthr,LBTthr,RDUthr,ILMthr&var=location,data_hourly,precip,watertemp,watertempmean&start=1950-01-01%2000:00&end=2020-01-28%2023:59&int=0%20SECOND&output=csv&attr=var,value,value_accum,unit,score,nettype,vartype,obtype,obnum,location,datetime&order=datetime,location&hash= errors: Time frequency must be a positive value help: For help, please contact the NC Climate Office at sco@climate.ncsu.edu or 919-515-3056

Expected Results:

A CSV with the data requeested.

API Version Used:

1.0.794-beta (752c951)

**Comment by jamcguir** [comment]
Fixed with latest update at https://github.ncsu.edu/ncsco/api/commit/bd261faa4a5684864d1974ff31ead6ddf88abd45
