### ISSUE TITLE
HTTP 504 error for select months

### ISSUE THREAD

**Issue by sheilasaia** [ncsco/api-help#29]
Description of problem:
I'm getting an HTTP 504 timeout error for certain months of a NCSU network data query and I'm not sure why. There should only be ~60 observations expected so it wouldn't be timing out because it was too large. So far I've run effective query using the same format for the ASOS, AWOS, ECONET, and COOP stations for the precip1m variable, 1 day interval, from Jan 1, 2015 to Dec 31, 2016 without any issues. All other settings were default.

Steps to Reproduce:
1. This runs and I can get the data without any issues: `https://climate.ncsu.edu/api/beta/data.php?var=precip1m&loc=type=NCSU&state=NC&int=1%20day&start=2015-04-01&end=2015-04-30&output=csv&hash=**MYAPIKEY**`
2. This times out: `https://climate.ncsu.edu/api/beta/data.php?var=precip1m&loc=type=NCSU&state=NC&int=1%20day&start=2015-05-01&end=2015-05-31&output=csv&hash=**MYAPIKEY**`
3. I also tried this but would prefer not needing to define individual site names in the query (i.e., loc=CAMP rather than the more generic loc=type=NCSU used in 1 and 2). I don't know the site names but want as much information as is available. This doesn't time out: `https://climate.ncsu.edu/api/beta/data.php?var=precip1m&loc=CAMP&state=NC&int=1%20day&start=2015-05-01&end=2015-05-31&output=csv&hash=**MYAPIKEY**`

Note: The only difference between steps 1 and 2 are the start and end dates. I'm not sure why loc=type=NCSU stops working in step 2.

Actual Results:
Step 1 and 3 generate a CSV object with a commented out header (see Expected Results below). Step 2 generates an empty object with the following body:

_Response [https://climate.ncsu.edu/api/beta/data.php?var=precip1m&loc=type=NCSU&state=NC&int=1%20day&start=2015-06-01&end=2015-06-02&output=csv&hash=**MYAPIKEY**]
  Date: 2020-09-14 20:35
  Status: 504
  Content-Type: text/html
  Size: 92 B
504 Gateway Time-out
The server didn't respond in time._

Expected Results:
Steps 1 and 3 generate the following output (CSV object):

_Response [https://climate.ncsu.edu/api/beta/data.php?var=precip1m&loc=CAMP&state=NC&int=1%20day&start=2015-06-01&end=2015-06-02&output=csv&hash=**MYAPIKEY**]
  Date: 2020-09-15 00:49
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 2.57 kB
North Carolina State Climate Office
N.C. State University
Web: https://climate.ncsu.edu
Email: sco@climate.ncsu.edu
Phone: 919-515-3056
For help with your request, include "&help" in the URL above
Submit or view bugs and issues at: https://github.com/ncsco/api-help/issues
..._

API Version Used:
Beta version available via: https://climate.ncsu.edu/api/beta/ .

Additional info:
I can't think of any additional information, but please let me know if I can further clarify the issue.

[x] I have removed my user hash from this post

**Comment by jamcguir** [comment]
Sorry for the delayed response.

Due to code changes (and fixes from #31 ), this issue appears to be fixed.

Please try again to confirm

**Comment by sheilasaia** [comment]
Yep! Appears great on my end, @jamcguir! Thank you. Closing this issue. 🎉
