### ISSUE TITLE
API bug

### ISSUE THREAD

**Issue by hadinon** [ncsco/api-help#3]
This request only works sometimes: http://nc-climate.ncsu.edu/api/alpha/api_request.php?loc=station=317069&attr=value,count,unit,type,score&var=tempmax&int=1%20day&start=-7%20week&end=-1%20day

...appears to work on web1 but not web2

**Comment by jamcguir** [comment]
Cannot duplicate, previous commits fixed the issue. Reopen if you run into it again.
