### ISSUE TITLE
extra commas in NOS network location name field causing downstream analysis issues

### ISSUE THREAD

**Issue by sheilasaia** [ncsco/api-help#30]
Description of problem:

There are several comma issues in the NOS network dataset that are causing hiccups for CSV outputs and downstream analysis of the CSV outputs.

There are no issues with the data pull from the API. But the format of the data itself is causing downstream issues.

Actual Results:

There are six stations that have a comma and/or a ", NC" in the Location Name field that's making things a little difficult for automating data pulls from the API using the CSV format output.

Expected Results:

I'm attaching what I'd suggest for the naming convention of the six sites (see the image below called "original" for the original names and the image called "suggested" for my suggestions highlighted in red).

### original
![original](https://user-images.githubusercontent.com/12959101/106080151-87145a00-60e4-11eb-872e-b80e60401065.png)

### suggested edits
![suggested](https://user-images.githubusercontent.com/12959101/106080382-ef633b80-60e4-11eb-87b1-8aaba9c1dff2.png)

API Version Used:

Beta version (available https://climate.ncsu.edu/api/beta/)

Additional info:

[x] I have removed my user hash from this post

**Comment by jamcguir** [comment]
The station metadata tables have been updated to remove commas. Please try again and confirm that this fixes your issue.

**Comment by sheilasaia** [comment]
Thanks so much @jamcguir! 🎉 Will try next week and let you know.

**Comment by sheilasaia** [comment]
Working well on my end!
