### ISSUE TITLE
THREADEX network data access issue

### ISSUE THREAD

**Issue by sheilasaia** [ncsco/api-help#31]
Description of problem:
I'm trying to pull TREADEX network data from 2015 and 2016. I used the API builder to generate the query below and it says I should expect 30 outputs but I'm getting 0 outputs.

Steps to Reproduce:
1. use API builder to make query for TREADEX site (with hash removed)
```
https://api.climate.ncsu.edu/data?loc=AVLthr&var=precip1m&start=2015-01-01 00:00&end=2015-01-31 23:59&int=1 DAY&output=csv attr=location,datetime,var,value,value_accum,unit,score,nettype,vartype,obtype,obnum,obtime&hash=####
```

2. get url from API builder

3. enter url into browser

Actual Results:
Seeing no observations. "No locations match your criteria."
![image](https://user-images.githubusercontent.com/12959101/108446704-8aef5400-722c-11eb-9acb-dbb5d2573cdb.png)

Expected Results:
Expect to see 30 observations.
![image](https://user-images.githubusercontent.com/12959101/108446556-52e81100-722c-11eb-9299-76a037bf81a2.png)

API Version Used:
Not sure where to find this on https://api.climate.ncsu.edu/.

Additional info:
Ideally, I would also get all TREADEX sites with `loc=type=THREADEX` but that's also not working. That query I built in R and is below (with hash removed).
```
https://api.climate.ncsu.edu/data.php?loc=type=THREADEX&state=NC&var=precip1m&start=2015-01-01&end=2015-01-31&int=1%20day&output=csv&attr=location,datetime,var,value,value_accum,unit,score,nettype,vartype,obtype,obnum,obtime&hash=####
```

[x] I have removed my user hash from this post

**Comment by sheilasaia** [comment]
Ahh, I'm seeing that there are no THREADEX stations on the "Networks" page. Maybe this is the issue? I had previously downloaded data for 8 stations in 2016 and they all seem to be showing up on the API Builder now.

![image](https://user-images.githubusercontent.com/12959101/108447743-6b592b00-722e-11eb-8654-55b7f4496a2c.png)

**Comment by jamcguir** [comment]
Issue has been resolved. ThreadEx stations were flagged as "not avaiable" due to another product. New API only flag added to resolve conflicts

**Comment by sheilasaia** [comment]
Yay 🎉 ! Thanks, @jamcguir!
