### ISSUE TITLE
Adding lat/lon to query results in SQL error

### ISSUE THREAD

**Issue by rvcumbie** [ncsco/api-help#32]
Description of problem:
I'm requesting daily airtempmax2m and airtempmin2m. Works fine. Adding 'lat' and 'lon' to my query results in it breaking

Steps to Reproduce:
1. Running: https://api.climate.ncsu.edu/data?loc=317079&var=airtempmax2m,airtempmin2m&start=2020-01-01%2000:00&end=2022-10-26%2023:59&int=1%20DAY&output=csv&attr=location,datetime,var,value,unit,obtime&timezone=UTC&hash= (works!)
2. Adding lat/lon: https://api.climate.ncsu.edu/data?loc=317079&var=airtempmax2m,airtempmin2m,lat,lon&start=2020-01-01%2000:00&end=2022-10-26%2023:59&int=1%20DAY&output=csv&attr=location,datetime,var,value,unit,obtime&timezone=UTC&hash= (results in error!)

Actual Results:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'MV' in 'where clause' with query: INSERT INTO tmp.API_d6f4f2abe505c4cc6b61442dcfc49748_data (location,network,ob,ob_tz,obdate,obtime,obtime_tz,obtype,period_float,ins_datetime,ins_date,ins_diff_sec,ins_abs_diff_sec,ins_rank,agg_datetime,agg_date,sum_datetime,tempmax,tempmaxflag,tempmin,tempminflag) SELECT station as `location`,"coop" as `network`,ob as `ob`,"-05:00" as `ob_tz`,DATE(ob) as `obdate`,CONVERT_TZ(ob,"-05:00","UTC") as `obtime`,"UTC" as `obtime_tz`,obtype as `obtype`,(TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440) as `period_float`,TIMESTAMPADD(DAY, ROUND((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00") as `ins_datetime`,TIMESTAMPADD(DAY, FLOOR((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),DATE(ob))/1440))*1, "2020-01-01 00:00:00") as `ins_date`,TIMESTAMPDIFF(SECOND,CONVERT_TZ(TIMESTAMPADD(DAY, ROUND((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00"),"UTC","-05:00"),ob) as `ins_diff_sec`,ABS(TIMESTAMPDIFF(SECOND,CONVERT_TZ(TIMESTAMPADD(DAY, ROUND((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00"),"UTC","-05:00"),ob)) as `ins_abs_diff_sec`,IF(TIMESTAMPDIFF(SECOND,CONVERT_TZ(TIMESTAMPADD(DAY, ROUND((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00"),"UTC","-05:00"),ob) = 0, 1, NULL) as `ins_rank`,TIMESTAMPADD(DAY, CEIL((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00") as `agg_datetime`,TIMESTAMPADD(DAY, FLOOR((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),DATE(ob))/1440))*1, "2020-01-01 00:00:00") as `agg_date`,TIMESTAMPADD(DAY, FLOOR((TIMESTAMPDIFF(MINUTE,CONVERT_TZ("2020-01-01 00:00:00","UTC","-05:00"),ob)/1440))*1, "2020-01-01 00:00:00") as `sum_datetime`,tempmax as `tempmax`,tempmaxflag as `tempmaxflag`,tempmin as `tempmin`,tempminflag as `tempminflag` FROM cronos.daily AS d WHERE d.station IN ("317079") AND MV IN ("D") AND ob >= CONVERT_TZ("2019-12-31 00:00:00","UTC","-05:00") AND ob <= CONVERT_TZ("2022-10-27 23:59:59","UTC","-05:00")

Expected Results:
Data!

API Version Used:
Whatever the latest version is as of 10/28 (looks like the last update was 10/7)

Additional info:
I've tried this with different stations, start/end dates, obtypes, and time zones, all with the same result. 

[X] I have removed my user hash from this post

**Comment by jamcguir** [comment]
Resolved issue with patch at https://github.ncsu.edu/ncsco/api/commit/6087e6b772aefcbea76782b656d33a35ea6fa0cf
