### ISSUE TITLE
ASOS daily tempmax/min data unavailable before 2005

### ISSUE THREAD

**Issue by daviswx** [ncsco/api-help#33]
Description of problem:
I was notified about this by Amy Buckalew, one of Dr. Brian McAdoo's students at Duke who is pulling historical data for a project investigating extreme weather events.

She mentioned that tempmax and tempmin data from KRDU was missing before January 1, 2005. Sure enough, the airtempmax and airtempmax2m parameters show as "MV" until January 1, 2005, when they suddenly become available. Note that data from the co-located COOP (317069) is available throughout this time.

I spot-checked a few other ASOS stations (KGSO, KILM) and noticed the same behavior there.

Steps to Reproduce:
1. Request airtempmax and/or airtempmax2m (or the minimum temperature equivalents), aggregated by day, from an ASOS station such as KRDU. ([example](https://api.climate.ncsu.edu/data?loc=KRDU&var=airtempmax,airtempmax2m&start=2004-01-01%2000:00&end=2006-12-31%2023:59&int=1%20DAY&obtype=D,H&attr=location,datetime,var,value,value_accum,unit,score,nettype,paramtype,obtype,obnum,obtime&hash=JustTestAMove141))
2. View the results
3. (Don't) profit

Actual Results:
MVs in the results through the end of 2004

Expected Results:
Calculated max/min temperatures for each day

API Version Used:
The current version as of Dec 7, 2022

Additional info:

[ ] I have removed my user hash from this post

**Comment by jamcguir** [comment]
This is related to ingest or old data using Integrated Surface Data (ISD) dataset. 

According to [documentation](https://www.ncei.noaa.gov/data/global-hourly/doc/isd-format-document.pdf), it should be under the **KA1-KA4** (Extreme Temperature) section. But it was often found to be missing for older datasets.

Fix is for data ingest to use the METAR code _embeded within_ the **REM** (Remarks) data section and parse through that. For past ASOS/AWOS data, ISD values are set in the order of

1. Mandatatory Data Section, if set, 
2. Additional Data Section, if set
3. Remarks Section METAR code, if available

Using this process on a test, data is retrieved as expected.

Once historical ingest is complete, I will test again

**Comment by jamcguir** [comment]
Closing this issue, as the historical ASOS data re-ingest is complete.

Please note that there are instances of data row not having EITHER (1) an expected METAR observation, (2)  the METAR 24-hour temperatures, or (3) the ISD coding it correct for FM-15/FM-16 (METAR/SPECIAL) weather reports., such as KRDU for 2004-01-17 23:51 EST.

This data is available in a different data structure (SOD, or Summary Of Day Report), which would need to be addressed in a future update.
