### ISSUE TITLE
API returning QCF for station metadata variables

### ISSUE THREAD

**Issue by gsbuol** [ncsco/api-help#34]
Description of problem:
API returning QCF for station metadata variables

Steps to Reproduce:
1.Use Builder
2.Select station metadata variable (i.e. location) for CSV output
3.

Actual Results:
QCF is returned for location ID

Expected Results:
ROCK for Rocky Mount station, KINS for Kinston Station

API Version Used:

Additional info:
https://api.climate.ncsu.edu/data?loc=KINS,ROCK&var=location,name,city,county,state,lat,lon,elev&start=2023-06-10 00:00&end=2023-06-14 23:59&int=1 DAY&output=csv&attr=var,value&hash=

All station metadata variables returning QCF.

[ X] I have removed my user hash from this post

**Comment by jamcguir** [comment]
Fixed with commit 2e091a5a9940ce4fa6208aef74bdfb55e1d98a8d
