### ISSUE TITLE
Datetime variable value not returned

### ISSUE THREAD

**Issue by gsbuol** [ncsco/api-help#35]
Description of problem:
When an estimated ET variable is included in the variable list with the datetime variable, the datetime value is not returned using CSV output.

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

API Version Used:

Additional info:
Example where datetime value is not returned:
https://api.climate.ncsu.edu/data?loc=ROCK&var=location,datetime,airtempmin2m,airtempmax2m,airtempavg2m,precip1m,growdegday2m:56,evaptrans_pm,evaptrans2m_pm&start=2023-05-01 00:00&end=2023-05-10 23:59&int=1 DAY&output=csv&attr=value&hash=

In the following case, the datetime value is returned (ET variables removed):
https://api.climate.ncsu.edu/data?loc=ROCK&var=location,datetime,airtempmin2m,airtempmax2m,airtempavg2m,precip1m,growdegday2m:56&start=2023-05-01 00:00&end=2023-05-10 23:59&int=1 DAY&output=csv&attr=value&hash=

[ X] I have removed my user hash from this post

**Comment by jamcguir** [comment]
More testing is required, but I have an API version with a patch. To test it, change the URL from 
   "/data?"
And change it to
   "**/testing**/data?"

The link to test would be 
https://api.climate.ncsu.edu/testing/data?loc=ROCK&var=location,datetime,airtempmin2m,airtempmax2m,airtempavg2m,precip1m,growdegday2m:56,evaptrans_pm,evaptrans2m_pm&start=2023-05-01 00:00&end=2023-05-10 23:59&int=1 DAY&output=csv&attr=value&hash=

Please let me know if this is the desired output

**Comment by gsbuol** [comment]
The test API version with the patch is working correctly. Thanks.

**Comment by jamcguir** [comment]
Operational API version fixed with commit e17e2f6578fc8f583e096d262b165d322825d49e
