### ISSUE TITLE
tempavg not in output

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#6]
var tempavg not showing up in results when using ASOS data
url: http://climate.ncsu.edu/api/alpha/api_request.php?&var=lat,lon,datetime,tempavg,ws,wd,precip&loc=state=NC,SC%20AND%20type=ASOS&start=2014-06-01%2007:00:00&end=2014-07-01%2007:00:00&int=12%20hour&obtype=H&timezone=EST&outfile=data2014&qclimit=1

**Comment by jamcguir** [comment]
Resolved in ncsco/api@c1d236b99bc845bffd91226269968fa3cf31bf65
