### ISSUE TITLE
incorrect units in output

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#8]
Metadata says slp press units of output are in mb for ASOS - but clearly looks like inHg.

API string:
http://climate.ncsu.edu/api/alpha/api_request.php?&var=press&loc=state=NC,SC%20AND%20type=ASOS&start=2014-06-01%2007:00:00&end=2014-07-01%2007:00:00&int=12%20hour&obtype=H&timezone=EST&qclimit=1

**Comment by jamcguir** [comment]
This was a database definition issue. Resolved.

Introduced another issue related to order of operations with selecting the variable, but fixed in ncsco/api@/2b95014f90d873a2fb999e57f66ada9ba6cc6795
