### ISSUE TITLE
units not output when requested

### ISSUE THREAD

**Issue by apsims2001** [ncsco/api-help#9]
help doc specifies the following options:
&attr=value,unit,score,type  as possible attributes to display.
unit never is displayed in output.

Also,
count is also an option, but is not listed in help doc.

API URL:
http://climate.ncsu.edu/api/alpha/api_request.php?&var=temp&loc=state=NC,SC%20AND%20type=ASOS&start=2014-06-01%2007:00:00&end=2014-07-01%2007:00:00&int=12%20hour&obtype=H&timezone=EST&qclimit=1&attr=value,count,unit,type,score

**Comment by jamcguir** [comment]
Fixed in ncsco/api@2b95014f90d873a2fb999e57f66ada9ba6cc6795
